function chnName = getChnName(numChn)

if numChn == 30
    chnName = {'S1D1 Middle Posterior FEF Left',...
        'S1D2 Posterior to sPCS/tgPSC Left',...
        'S1D3 Middle FEF Left',...
        'S1D4 sPCS/tgPCS Left',...
        'S2D1 Posterior FEF Left',...
        'S2D2 Inferior to FEF Left',...
        'S3D3 Anterior FEF Left',...
        'S3D4 iPCS/tgPCS Left',...
        'S3D5 Anterior to FEF Left',...
        'S3D6 iPCS Left',...
        'S4D9 Anterior FEF Right',...
        'S4D10 iPCS/tgPCS Right',...
        'S4D11 Anterior to FEF Right',...
        'S4D12 iPCS Right',...
        'S5D7 Middle Posterior FEF Right',...
        'S5D8 Posterior to sPCS/tgPSC Right',...
        'S5D9 Middle FEF Right',...
        'S5D10 sPCS/tgPCS Right',...
        'S6D7 Posterior to FEF Right',...
        'S6D8 Inferor to FEF Right',...
        'S7D16 Posterior STG/PT Left',...
        'S8D17 Posterior STG/PT Right',...
        'S9D13 IPS3/IPS2/SPL1 Left',...
        'S9D14 IPS3/antIPS/IPS4 Left',...
        'S10D13 IPS3/IPS2/SPL1 Right',...
        'S10D15 IPS3/antIPS/IPS4 Right',...
        'S11D13 Superior to IPS3/IPS2/SPL1 Left',...
        'S11D14 IPS4 Left',...
        'S12D13 Superior to IPS3/IPS2/SPL1 Right',...
        'S12D15 IPS4 Right'};
elseif numChns == 34
    chnName = {'Middle Posterior FEF Left',...
        'Posterior to sPCS/tgPSC Left',...
        'Middle FEF Left',...
        'sPCS/tgPCS Left',...
        'Posterior FEF Left',...
        'Inferior to FEF Left',...
        'Anterior FEF Left',...
        'iPCS/tgPCS Left',...
        'Anterior to FEF Left',...
        'iPCS Left',...
        'Anterior FEF Right',...
        'iPCS/tgPCS Right',...
        'Anterior to FEF Right',...
        'iPCS Right',...
        'Middle Posterior FEF Right',...
        'Posterior to sPCS/tgPSC Right',...
        'Middle FEF Right',...
        'sPCS/tgPCS Right',...
        'Posterior to FEF Right',...
        'Inferor to FEF Right',...
        'Post Posterior STG/PT Left',...
        'Posterior STG/PT Right',...
        'IPS3/IPS2/SPL1 Left',...
        'IPS3/antIPS/IPS4 Left',...
        'IPS3/latIPS/antIPS Left',...
        'IPS3/IPS2/SPL1 Right',...
        'IPS3/antIPS/IPS4 Right',...
        'IPS3/latIPS/antIPS Right',...
        'Superior to IPS3/IPS2/SPL1 Left',...
        'IPS4 Left',...
        'Superior to IPS3/IPS2/SPL1 Right',...
        'IPS4 Right',...
        'Ant Posterior STG/PT Left',...
        'Ant Posterior STG/PT Right'};
end
end