function [chnList, LSChnList] = getChnList(isNew)

% all 36 channels for fNIRS
if isNew
chnList = {'S1D1 Middle Posterior FEF Left',...
    'S1D2 Posterior to sPCS/tgPSC Left',...
    'S1D3 Middle FEF Left',...
    'S1D4 sPCS/tgPCS Left',...
    'S2D1 Posterior FEF Left',...
    'S2D2 Inferior to FEF Left',...
    'SS1',...
    'S3D3 Anterior FEF Left',...
    'S3D4 iPCS/tgPCS Left',...
    'S3D5 Anterior to FEF Left',...
    'S3D6 iPCS Left',...
    'S4D9 Anterior FEF Right',...
    'S4D10 iPCS/tgPCS Right',...
    'S4D11 Anterior to FEF Right',...
    'S4D12 iPCS Right',...
    'S5D7 Middle Posterior FEF Right',...
    'S5D8 Posterior to sPCS/tgPSC Right',...
    'S5D9 Middle FEF Right',...
    'S5D10 sPCS/tgPCS Right',...
    'S6D7 Posterior to FEF Right',...
    'S6D8 Inferor to FEF Right',...
    'SS2',...
    'S7D16 Posterior STG/PT Left',...
    'SS3',...
    'S8D17 Posterior STG/PT Right',...
    'SS4',...
    'S9D13 IPS3/IPS2/SPL1 Left',...
    'S9D14 IPS3/antIPS/IPS4 Left',...
    'S9D16 IPS3/latIPS/antIPS Left',...
    'SS5',...
    'S10D13 IPS3/IPS2/SPL1 Right',...
    'S10D15	IPS3/antIPS/IPS4 Right',...
    'S10D17 IPS3/latIPS/antIPS Right',...
    'SS6',...
    'S11D13	Superior to IPS3/IPS2/SPL1 Left',...
    'S11D14	IPS4 Left',...
    'S12D13	Superior to IPS3/IPS2/SPL1 Right',...
    'S12D15	IPS4 Right'};
    

LSChnList = {'S1D1 Middle Posterior FEF Left',...
    'S1D2 Posterior to sPCS/tgPSC Left',...
    'S1D3 Middle FEF Left',...
    'S1D4 sPCS/tgPCS Left',...
    'S2D1 Posterior FEF Left',...
    'S2D2 Inferior to FEF Left',...
    'S3D3 Anterior FEF Left',...
    'S3D4 iPCS/tgPCS Left',...
    'S3D5 Anterior to FEF Left',...
    'S3D6 iPCS Left',...
    'S4D9 Anterior FEF Right',...
    'S4D10 iPCS/tgPCS Right',...
    'S4D11 Anterior to FEF Right',...
    'S4D12 iPCS Right',...
    'S5D7 Middle Posterior FEF Right',...
    'S5D8 Posterior to sPCS/tgPSC Right',...
    'S5D9 Middle FEF Right',...
    'S5D10 sPCS/tgPCS Right',...
    'S6D7 Posterior to FEF Right',...
    'S6D8 Inferor to FEF Right',...
    'S7D16 Posterior STG/PT Left',...
    'S8D17 Posterior STG/PT Right',...
    'S9D13 IPS3/IPS2/SPL1 Left',...
    'S9D14 IPS3/antIPS/IPS4 Left',...
    'S9D16 IPS3/latIPS/antIPS Left',...
    'S10D13 IPS3/IPS2/SPL1 Right',...
    'S10D15	IPS3/antIPS/IPS4 Right',...
    'S10D17 IPS3/latIPS/antIPS Right',...
    'S11D13	Superior to IPS3/IPS2/SPL1 Left',...
    'S11D14	IPS4 Left',...
    'S12D13	Superior to IPS3/IPS2/SPL1 Right',...
    'S12D15	IPS4 Right'};

else
    chnList = {'S1D1 Middle Posterior FEF Left',...
    'S1D2 Posterior to sPCS/tgPSC Left',...
    'S1D3 Middle FEF Left',...
    'S1D4 sPCS/tgPCS Left',...
    'S2D1 Posterior FEF Left',...
    'S2D2 Inferior to FEF Left',...
    'SS1',...
    'S3D3 Anterior FEF Left',...
    'S3D4 iPCS/tgPCS Left',...
    'S3D5 Anterior to FEF Left',...
    'S3D6 iPCS Left',...
    'S4D9 Anterior FEF Right',...
    'S4D10 iPCS/tgPCS Right',...
    'S4D11 Anterior to FEF Right',...
    'S4D12 iPCS Right',...
    'S5D7 Middle Posterior FEF Right',...
    'S5D8 Posterior to sPCS/tgPSC Right',...
    'S5D9 Middle FEF Right',...
    'S5D10 sPCS/tgPCS Right',...
    'S6D7 Posterior to FEF Right',...
    'S6D8 Inferor to FEF Right',...
    'SS2',...
    'S7D16 Posterior STG/PT Left',...
    'SS3',...
    'S8D17 Posterior STG/PT Right',...
    'SS4',...
    'S9D13 IPS3/IPS2/SPL1 Left',...
    'S9D14 IPS3/antIPS/IPS4 Left',...
    'S9D16 IPS3/latIPS/antIPS Left',...
    'SS5',...
    'S10D13 IPS3/IPS2/SPL1 Right',...
    'S10D15	IPS3/antIPS/IPS4 Right',...
    'S10D17 IPS3/latIPS/antIPS Right',...
    'SS6',...
    'S11D13	Superior to IPS3/IPS2/SPL1 Left',...
    'S11D14	IPS4 Left',...
    'S12D13	Superior to IPS3/IPS2/SPL1 Right',...
    'S12D15	IPS4 Right',...
    'S13D28 Posterior STG/PT',...
    'SS7',...
    'S14D29 Posterior STG/PT',...
    'SS8'};
    

LSChnList = {'S1D1 Middle Posterior FEF Left',...
    'S1D2 Posterior to sPCS/tgPSC Left',...
    'S1D3 Middle FEF Left',...
    'S1D4 sPCS/tgPCS Left',...
    'S2D1 Posterior FEF Left',...
    'S2D2 Inferior to FEF Left',...
    'S3D3 Anterior FEF Left',...
    'S3D4 iPCS/tgPCS Left',...
    'S3D5 Anterior to FEF Left',...
    'S3D6 iPCS Left',...
    'S4D9 Anterior FEF Right',...
    'S4D10 iPCS/tgPCS Right',...
    'S4D11 Anterior to FEF Right',...
    'S4D12 iPCS Right',...
    'S5D7 Middle Posterior FEF Right',...
    'S5D8 Posterior to sPCS/tgPSC Right',...
    'S5D9 Middle FEF Right',...
    'S5D10 sPCS/tgPCS Right',...
    'S6D7 Posterior to FEF Right',...
    'S6D8 Inferor to FEF Right',...
    'S7D16 Posterior STG/PT Left',...
    'S8D17 Posterior STG/PT Right',...
    'S9D13 IPS3/IPS2/SPL1 Left',...
    'S9D14 IPS3/antIPS/IPS4 Left',...
    'S9D16 IPS3/latIPS/antIPS Left',...
    'S10D13 IPS3/IPS2/SPL1 Right',...
    'S10D15	IPS3/antIPS/IPS4 Right',...
    'S10D17 IPS3/latIPS/antIPS Right',...
    'S11D13	Superior to IPS3/IPS2/SPL1 Left',...
    'S11D14	IPS4 Left',...
    'S12D13	Superior to IPS3/IPS2/SPL1 Right',...
    'S12D15	IPS4 Right',...
    'S13D28 Posterior STG/PT',...
    'S14D29 Posterior STG/PT'};

end
    
end
    
    
    
