% split into single and multi groups.
% new. Use trials from dcNew var
% For sbj 08 and 10

function plotPerformanceBarChartROINames_Special(sbjNum,varName,tInd,featureName,saveOp)

figSaveDir = ['C:\Users\mn0mn\Documents\ResearchProjects\spatailAttentionProject\ProcessedDatafNIRS\Experiment' num2str(sbjNum) '\Figures\Classification'];

SSidx = [7,22,24,26,30,34,39,41];

fs = 50;
timePt = (0:0.5*fs:12*fs)+2*fs;

chnName = {'Middle Posterior FEF Left',...
    'Posterior to sPCS/tgPSC Left',...
    'Middle FEF Left',...
    'sPCS/tgPCS Left',...
    'Posterior FEF Left',...
    'Inferior to FEF Left',...
    'Anterior FEF Left',...
    'iPCS/tgPCS Left',...
    'Anterior to FEF Left',...
    'iPCS Left',...
    'Anterior FEF Right',...
    'iPCS/tgPCS Right',...
    'Anterior to FEF Right',...
    'iPCS Right',...
    'Middle Posterior FEF Right',...
    'Posterior to sPCS/tgPSC Right',...
    'Middle FEF Right',...
    'sPCS/tgPCS Right',...
    'Posterior to FEF Right',...
    'Inferor to FEF Right',...
    'Post Posterior STG/PT Left',...
    'Posterior STG/PT Right',...
    'IPS3/IPS2/SPL1 Left',...
    'IPS3/antIPS/IPS4 Left',...
    'IPS3/latIPS/antIPS Left',...
    'IPS3/IPS2/SPL1 Right',...
    'IPS3/antIPS/IPS4 Right',...
    'IPS3/latIPS/antIPS Right',...
    'Superior to IPS3/IPS2/SPL1 Left',...
    'IPS4 Left',...
    'Superior to IPS3/IPS2/SPL1 Right',...
    'IPS4 Right',...
    'Ant Posterior STG/PT Left',...
    'Ant Posterior STG/PT Right'};

varName(SSidx,:) = [];

% chnName = {'S1D1','S1D2','S1D3','S1D4','S2D1','S2D2','S3D3','S3D4','S3D5','S3D6',...
%     'S4D9','S4D10','S4D11','S4D12','S5D7','S5D8','S5D9','S5D10','S6D7','S6D8',...
%     'S7D18','S8D19','S9D13','S9D14','S9D16','S10D13','S10D15','S10D17',...
%     'S11D13','S11D14','S12D13','S12D15','S13D28','S14D29'};

% plot performance as bar chart for each channel
figure();
X = categorical(chnName);
X = reordercats(X,chnName);

bar(X,varName(:,tInd));
title(sprintf('Sbj %s: %s at %ss',num2str(sbjNum),featureName,num2str(timePt(tInd))));
ylim([0 1]);

if saveOp == 1
    fn = sprintf('Sbj%s%ss%s',num2str(sbjNum),featureName,num2str(timePt(tInd)));
    print(gcf,[figSaveDir filesep fn],'-dpng','-r250');
end

end
